version: "3.9"
services:
  frontend:
    image: frontend:latest
    ports:
      - "3000:3000"
    environment:
      - BACKEND_API_URL=http://backend:8000
      - BACKEND_RESOURCES_URL=http://pixs.it.dh-karlsruhe.de:8000
  backend:
    image: backend:latest
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=backend,localhost,pixs.it.dh-karlsruhe.de